# Generated by Django 2.1.5 on 2019-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='list_date',
            field=models.DateField(auto_now=True),
        ),
    ]
