# Generated by Django 2.1.5 on 2019-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='title',
        ),
    ]
